config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get'login'=>'sessions#new'
  post'login'=>'sessions#create'
  delete'logout'=>'sessions#destroy'
  resources :listings
  resources :users
  resources :account_activations,only:[:edit]

   root 'listings#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings, dependent: :destroy
  attr_accessor :activation_token
  before_create :create_activation_digest
  before_save{self.email=email.downcase}
  validates :first_name, :last_name, presence:true
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence:true,length:{maximum:255},
            format:{with:VALID_EMAIL_REGEX}, uniqueness:{case_sensitive:false}
  validates :password,length: {minimum:6}

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost=ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string,cost:cost)
  end

  def authenticate_my_user? string
    self.password == string
  end

  def authenticated?(attribute,token)
    digest=send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  private
  # Creates and assigns the activation token and digest.
  def create_activation_digest
  self.activation_token=User.new_token
  self.activation_digest=User.digest(activation_token)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @types = [["Buider", 'builder', {:class=>"bold"}], ["Customer", 'customer']]
   # @ranges = [["A", 1, {:class=>"bold"}], ["B", 2], ["C", 3]] # {:class=> "bold"} is optional, use only if you need html class for option tag.
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info]="Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def delete
    User.find(params[:id]).destroy
    flash[:success]="User deleted"
    redirect_to users_url
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]="Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @listings = @user.listings
    @listing = @user.listings.build
  end

  private
  def user_params
    params.require(:user).permit(:street_address, :first_name, :last_name, :age_range, :price_range, :have_agent, :want_agent, :email,
                                    :password, :user_as, listing_images_attributes:[:url,:description,:_destroy,:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    !current_user.nil? && (current_user.user_as == "Admin".downcase || current_user.user_as == "Builder".downcase)
  end
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<%provide(:title,'Edit User')%>
<% @age_ranges = [["18-25", '18-25', {:class=>"bold"}], ["26-34", '26-34'], ["35-44", '35-44'], ["45-59", '45-59'], ["60+", '60+']]
   @price_ranges = [["Under 500K", 'Under 500K', {:class=>"bold"}], ["500K-699K", '500K-699K'], ["700K-899K", '700K-899K'], ["900K-1.1M,", '900K-1.1M,'], ["1.1M+", '1.1M+']]%>
<h1>Edit user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=form_for(@user)do|f|%>
        <%=render'shared/error_messages',object:f.object%>
        <%=f.label :first_name%>
        <%=f.text_field :first_name%>

        <%=f.label :last_name%>
        <%=f.text_field :last_name%>

        <%= f.select :age_range, options_for_select(@age_ranges) %>
        <%= f.select :price_range, options_for_select(@price_ranges) %>

        <%=f.label :password%>
        <%=f.password_field :password%>

        <%=f.label :have_agent%>
        <%=f.check_box :have_agent%>

        <%=f.label :want_agent%>
        <%=f.check_box :want_agent%>

        <%=f.submit"Create my account",class:"btn btn-primary"%>
    <%end%>
  </div>
</div>

app/views/users/index.html.erb
<%provide(:title,'All users')%>

<ul class="users">
  <h1>All users</h1>
  <%@users.each do|user|%>
      <li>
        <%=link_to user.first_name,user%> -- Type of user: <%=link_to user.user_as,user%>

      </li>
  <%end%>
</ul>

app/views/users/new.html.erb
<%provide(:title,'User')%>
<% @age_ranges = [["18-25", '18-25', {:class=>"bold"}], ["26-34", '26-34'], ["35-44", '35-44'], ["45-59", '45-59'], ["60+", '60+']]
   @price_ranges = [["Under 500K", 'Under 500K', {:class=>"bold"}], ["500K-699K", '500K-699K'], ["700K-899K", '700K-899K'], ["900K-1.1M,", '900K-1.1M,'], ["1.1M+", '1.1M+']]%>
<h1>Create user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=form_for(@user)do|f|%>
        <%=render'shared/error_messages',object:f.object%>
        <%=f.label :first_name%>
        <%=f.text_field :first_name%>

        <%=f.label :last_name%>
        <%=f.text_field :last_name%>

        <%=f.label :email%>
        <%=f.email_field :email%>

        <%= f.select :age_range, options_for_select(@age_ranges) %>
        <%= f.select :price_range, options_for_select(@price_ranges) %>

        <%=f.label :password%>
        <%=f.password_field :password%>

        <%=f.label :have_agent%>
        <%=f.check_box :have_agent%>

        <%=f.label :want_agent%>
        <%=f.check_box :want_agent%>

        <%=f.submit"Create my account",class:"btn btn-primary"%>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.first_name %>
      </h1>
    </section>
  </aside>
  <% if admin? %>
      <table id="listings_lists">
        <thead>
        <tr>
          <th>Street address</th>
          <th>Category</th>
          <th>Price</th>
        </tr>
        </thead>
        <tbody>
        <% @user.listings.each do |product| %>
            <tr>

              <td><%= product.street_address %></td>
              <td><%= product.price %></td>
              <td><%= link_to(product.id, product) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <%=link_to "Create listing", new_listing_path, :class => "btn btn-success" %>
  <%end%>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>