config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get'login'=>'sessions#new'
  post'login'=>'sessions#create'
  delete'logout'=>'sessions#destroy'
  resources :listings
  resources :users
  resources :account_activations,only:[:edit]

   root 'listings#index'

end

app/views/layouts/_header.html.erb
<header class="header-terdown">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <div class="logo">
          <%= image_tag("logo-houses.jpg", width: '180', alt: 'Site Logo', class: "img-responsive") %>
        </div>
      </div>
      <div class="col-xs-9" style="padding-top: 10px">
        <div class="row">
          <div class="col-xs-4"></div>
          <div class="col-xs-4 text-right">
            <p class="telefono-header"><a href="tel:01800123456" target="_blank">01 (800) TEARDOWN</a></p>
            <h2 class="telefono-header"><a href="tel:01800123456" target="_blank">01 (800) 227-12345</a></h2>
          </div>
          <div class="col-xs-4">
            <div class="btn-group form-iniciar-sesion">
              <a class="btn btn-default btn-block force-open dropdown-toggle" data-toggle="dropdown">User  <span class="fa fa-user"></span></a>
              <!-- INICIO DROPDOWN FORMULARIO INICIO SESIÓN -->
              <ul class="dropdown-menu pull-right" role="menu">
                <li>
                  <%=form_for(:session,url:login_path)do|f|%>
                      <div class="input-group" style="padding: 5px;">
                        <span class="input-group-addon">
                         <i class="fa fa-envelope"></i>
                        </span>
                        <%=f.email_field :email,class:'form-control'%>
                      </div>
                      <div class="input-group" style="padding: 5px;">
                        <span class="input-group-addon">
                          <i class="fa fa-lock"></i>
                        </span>
                        <%=f.password_field :password,class:'form-control'%>
                      </div>

                      <div class="row popover-iniciar-sesion" style="padding: 5px;">
                        <div class="col-xs-12 text-center">
                      <%=f.submit "Submit",class:"btn btn-primary"%>
                        </div>
                      </div>
                      <div class="row popover-iniciar-sesion margenTop-2">
                        <div class="col-xs-12 text-center">
                          <p><%=link_to ("Register <i class='fa fa-angle-right'></i>").html_safe,new_user_path%></p>
                        </div>
                      </div>
                  <%end%>
                </li>
              </ul>
              <!-- FIN DROPDOWN FORMULARIO INICIO SESIÓN -->
            </div>
            <%=link_to "Log out",logout_path,method:"delete"%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav role="navigation" class="navbar navbar-default no-print">
    <div class="container">
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%=link_to "LISTINGS",listings_path%></li>
          <li><%=link_to "USERS", users_path %></li>
          <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" title="PROFILE">MY PROFILE <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%=link_to "Profile",current_user%></li>
              <li><%=link_to "Settings",edit_user_path(current_user)%></li>
            </ul>
          </li>
              <%end%>
          <li><a href="/Contacto">CONTACTO</a></li>
        </ul>
        <ul class="redes-sociales">
          <li><a href="https://twitter.com/carflexmx" target="_blank" title="Twitter"><span class="fa fa-twitter-square"></span></a></li>
          <li><a href="https://www.facebook.com/angel.guemezrodriguez" target="_blank" title="Facebook"><span class="fa fa-facebook"></span></a></li>
          <li><a href="https://plus.google.com/u/0/110240012850156623865" target="_blank" title="Google+"><span class="fa fa-google-plus"></span></a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jQueryCarrusel' %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <%= csrf_meta_tags %>
</head>
<!--<body class="<%= params[:controller]%>">-->
<body class="<%= controller.controller_name %> <%= controller.action_name %>">
<%=render 'layouts/header'%>

<%flash.each do|message_type,message|%>
    <div class="alert alert-<%=message_type%>"><%=message%></div>
<%end%>
      <%= yield %>
<%=debug(params) if Rails.env.development?%>
</body>

<%= javascript_tag do %>
    $('.dropdown-menu').find('form').click(function (e) {
    e.stopPropagation();
    $(".form-iniciar-sesion .alert .close").on("click", function(){
    $(this).parent().remove();
    });
    });
<% end %>

</html>